# config/routes.yaml
post_list:
    path: /posts
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\PostController::all

    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\BlogController